// Generated by gencpp from file driver/config_armRequest.msg
// DO NOT EDIT!


#ifndef DRIVER_MESSAGE_CONFIG_ARMREQUEST_H
#define DRIVER_MESSAGE_CONFIG_ARMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace driver
{
template <class ContainerAllocator>
struct config_armRequest_
{
  typedef config_armRequest_<ContainerAllocator> Type;

  config_armRequest_()
    : base_angle_offset(0)
    , shoulder_angle_offset(0)
    , elbow_angle_offset(0)
    , wrist_angle_offset(0)
    , gripper_angle_offset(0)
    , wrist_rotate_angle_offset(0)  {
    }
  config_armRequest_(const ContainerAllocator& _alloc)
    : base_angle_offset(0)
    , shoulder_angle_offset(0)
    , elbow_angle_offset(0)
    , wrist_angle_offset(0)
    , gripper_angle_offset(0)
    , wrist_rotate_angle_offset(0)  {
  (void)_alloc;
    }



   typedef int8_t _base_angle_offset_type;
  _base_angle_offset_type base_angle_offset;

   typedef int8_t _shoulder_angle_offset_type;
  _shoulder_angle_offset_type shoulder_angle_offset;

   typedef int8_t _elbow_angle_offset_type;
  _elbow_angle_offset_type elbow_angle_offset;

   typedef int8_t _wrist_angle_offset_type;
  _wrist_angle_offset_type wrist_angle_offset;

   typedef int8_t _gripper_angle_offset_type;
  _gripper_angle_offset_type gripper_angle_offset;

   typedef int8_t _wrist_rotate_angle_offset_type;
  _wrist_rotate_angle_offset_type wrist_rotate_angle_offset;





  typedef boost::shared_ptr< ::driver::config_armRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::driver::config_armRequest_<ContainerAllocator> const> ConstPtr;

}; // struct config_armRequest_

typedef ::driver::config_armRequest_<std::allocator<void> > config_armRequest;

typedef boost::shared_ptr< ::driver::config_armRequest > config_armRequestPtr;
typedef boost::shared_ptr< ::driver::config_armRequest const> config_armRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::driver::config_armRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::driver::config_armRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::driver::config_armRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::driver::config_armRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::driver::config_armRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::driver::config_armRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::driver::config_armRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::driver::config_armRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::driver::config_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea70cecd00e14397f55e308d906e14d3";
  }

  static const char* value(const ::driver::config_armRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea70cecd00e14397ULL;
  static const uint64_t static_value2 = 0xf55e308d906e14d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::driver::config_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "driver/config_armRequest";
  }

  static const char* value(const ::driver::config_armRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::driver::config_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 base_angle_offset\n"
"int8 shoulder_angle_offset\n"
"int8 elbow_angle_offset\n"
"int8 wrist_angle_offset\n"
"int8 gripper_angle_offset\n"
"int8 wrist_rotate_angle_offset\n"
;
  }

  static const char* value(const ::driver::config_armRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::driver::config_armRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.base_angle_offset);
      stream.next(m.shoulder_angle_offset);
      stream.next(m.elbow_angle_offset);
      stream.next(m.wrist_angle_offset);
      stream.next(m.gripper_angle_offset);
      stream.next(m.wrist_rotate_angle_offset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct config_armRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::driver::config_armRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::driver::config_armRequest_<ContainerAllocator>& v)
  {
    s << indent << "base_angle_offset: ";
    Printer<int8_t>::stream(s, indent + "  ", v.base_angle_offset);
    s << indent << "shoulder_angle_offset: ";
    Printer<int8_t>::stream(s, indent + "  ", v.shoulder_angle_offset);
    s << indent << "elbow_angle_offset: ";
    Printer<int8_t>::stream(s, indent + "  ", v.elbow_angle_offset);
    s << indent << "wrist_angle_offset: ";
    Printer<int8_t>::stream(s, indent + "  ", v.wrist_angle_offset);
    s << indent << "gripper_angle_offset: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gripper_angle_offset);
    s << indent << "wrist_rotate_angle_offset: ";
    Printer<int8_t>::stream(s, indent + "  ", v.wrist_rotate_angle_offset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVER_MESSAGE_CONFIG_ARMREQUEST_H
