// Generated by gencpp from file driver/config_armRequest.msg
// DO NOT EDIT!


#ifndef DRIVER_MESSAGE_CONFIG_ARMREQUEST_H
#define DRIVER_MESSAGE_CONFIG_ARMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace driver
{
template <class ContainerAllocator>
struct config_armRequest_
{
  typedef config_armRequest_<ContainerAllocator> Type;

  config_armRequest_()
    : angle_offsets()  {
    }
  config_armRequest_(const ContainerAllocator& _alloc)
    : angle_offsets(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _angle_offsets_type;
  _angle_offsets_type angle_offsets;





  typedef boost::shared_ptr< ::driver::config_armRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::driver::config_armRequest_<ContainerAllocator> const> ConstPtr;

}; // struct config_armRequest_

typedef ::driver::config_armRequest_<std::allocator<void> > config_armRequest;

typedef boost::shared_ptr< ::driver::config_armRequest > config_armRequestPtr;
typedef boost::shared_ptr< ::driver::config_armRequest const> config_armRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::driver::config_armRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::driver::config_armRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::driver::config_armRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::driver::config_armRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::driver::config_armRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::driver::config_armRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::driver::config_armRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::driver::config_armRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::driver::config_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c19c548d8915eb1b329adf0e59179cb";
  }

  static const char* value(const ::driver::config_armRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c19c548d8915eb1ULL;
  static const uint64_t static_value2 = 0xb329adf0e59179cbULL;
};

template<class ContainerAllocator>
struct DataType< ::driver::config_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "driver/config_armRequest";
  }

  static const char* value(const ::driver::config_armRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::driver::config_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[] angle_offsets\n"
;
  }

  static const char* value(const ::driver::config_armRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::driver::config_armRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle_offsets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct config_armRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::driver::config_armRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::driver::config_armRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle_offsets[]" << std::endl;
    for (size_t i = 0; i < v.angle_offsets.size(); ++i)
    {
      s << indent << "  angle_offsets[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.angle_offsets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVER_MESSAGE_CONFIG_ARMREQUEST_H
