// Generated by gencpp from file driver/config_armResponse.msg
// DO NOT EDIT!


#ifndef DRIVER_MESSAGE_CONFIG_ARMRESPONSE_H
#define DRIVER_MESSAGE_CONFIG_ARMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace driver
{
template <class ContainerAllocator>
struct config_armResponse_
{
  typedef config_armResponse_<ContainerAllocator> Type;

  config_armResponse_()
    : succes(false)  {
    }
  config_armResponse_(const ContainerAllocator& _alloc)
    : succes(false)  {
  (void)_alloc;
    }



   typedef uint8_t _succes_type;
  _succes_type succes;





  typedef boost::shared_ptr< ::driver::config_armResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::driver::config_armResponse_<ContainerAllocator> const> ConstPtr;

}; // struct config_armResponse_

typedef ::driver::config_armResponse_<std::allocator<void> > config_armResponse;

typedef boost::shared_ptr< ::driver::config_armResponse > config_armResponsePtr;
typedef boost::shared_ptr< ::driver::config_armResponse const> config_armResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::driver::config_armResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::driver::config_armResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::driver::config_armResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::driver::config_armResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::driver::config_armResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::driver::config_armResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::driver::config_armResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::driver::config_armResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::driver::config_armResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "509793171e494962cd366ecf60e100e4";
  }

  static const char* value(const ::driver::config_armResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x509793171e494962ULL;
  static const uint64_t static_value2 = 0xcd366ecf60e100e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::driver::config_armResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "driver/config_armResponse";
  }

  static const char* value(const ::driver::config_armResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::driver::config_armResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool succes\n"
;
  }

  static const char* value(const ::driver::config_armResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::driver::config_armResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct config_armResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::driver::config_armResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::driver::config_armResponse_<ContainerAllocator>& v)
  {
    s << indent << "succes: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVER_MESSAGE_CONFIG_ARMRESPONSE_H
