// Generated by gencpp from file driver/control_armRequest.msg
// DO NOT EDIT!


#ifndef DRIVER_MESSAGE_CONTROL_ARMREQUEST_H
#define DRIVER_MESSAGE_CONTROL_ARMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace driver
{
template <class ContainerAllocator>
struct control_armRequest_
{
  typedef control_armRequest_<ContainerAllocator> Type;

  control_armRequest_()
    : base_angle(0)
    , base_speed(0)
    , shoulder_angle(0)
    , shoulder_speed(0)
    , elbow_angle(0)
    , elbow_speed(0)
    , wrist_angle(0)
    , wrist_speed(0)
    , gripper_angle(0)
    , gripper_speed(0)
    , wrist_rotate_angle(0)
    , wrist_rotate_speed(0)
    , time(0)  {
    }
  control_armRequest_(const ContainerAllocator& _alloc)
    : base_angle(0)
    , base_speed(0)
    , shoulder_angle(0)
    , shoulder_speed(0)
    , elbow_angle(0)
    , elbow_speed(0)
    , wrist_angle(0)
    , wrist_speed(0)
    , gripper_angle(0)
    , gripper_speed(0)
    , wrist_rotate_angle(0)
    , wrist_rotate_speed(0)
    , time(0)  {
  (void)_alloc;
    }



   typedef int16_t _base_angle_type;
  _base_angle_type base_angle;

   typedef uint8_t _base_speed_type;
  _base_speed_type base_speed;

   typedef int16_t _shoulder_angle_type;
  _shoulder_angle_type shoulder_angle;

   typedef uint8_t _shoulder_speed_type;
  _shoulder_speed_type shoulder_speed;

   typedef int16_t _elbow_angle_type;
  _elbow_angle_type elbow_angle;

   typedef uint8_t _elbow_speed_type;
  _elbow_speed_type elbow_speed;

   typedef int16_t _wrist_angle_type;
  _wrist_angle_type wrist_angle;

   typedef uint8_t _wrist_speed_type;
  _wrist_speed_type wrist_speed;

   typedef int16_t _gripper_angle_type;
  _gripper_angle_type gripper_angle;

   typedef uint8_t _gripper_speed_type;
  _gripper_speed_type gripper_speed;

   typedef int16_t _wrist_rotate_angle_type;
  _wrist_rotate_angle_type wrist_rotate_angle;

   typedef uint8_t _wrist_rotate_speed_type;
  _wrist_rotate_speed_type wrist_rotate_speed;

   typedef uint16_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::driver::control_armRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::driver::control_armRequest_<ContainerAllocator> const> ConstPtr;

}; // struct control_armRequest_

typedef ::driver::control_armRequest_<std::allocator<void> > control_armRequest;

typedef boost::shared_ptr< ::driver::control_armRequest > control_armRequestPtr;
typedef boost::shared_ptr< ::driver::control_armRequest const> control_armRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::driver::control_armRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::driver::control_armRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::driver::control_armRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::driver::control_armRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::driver::control_armRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::driver::control_armRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::driver::control_armRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::driver::control_armRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::driver::control_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd10510da7b0daa1c1d87a003f9b006d";
  }

  static const char* value(const ::driver::control_armRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd10510da7b0daa1ULL;
  static const uint64_t static_value2 = 0xc1d87a003f9b006dULL;
};

template<class ContainerAllocator>
struct DataType< ::driver::control_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "driver/control_armRequest";
  }

  static const char* value(const ::driver::control_armRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::driver::control_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 base_angle\n"
"uint8 base_speed\n"
"int16 shoulder_angle\n"
"uint8 shoulder_speed\n"
"int16 elbow_angle\n"
"uint8 elbow_speed\n"
"int16 wrist_angle\n"
"uint8 wrist_speed\n"
"int16 gripper_angle\n"
"uint8 gripper_speed\n"
"int16 wrist_rotate_angle\n"
"uint8 wrist_rotate_speed\n"
"uint16 time\n"
;
  }

  static const char* value(const ::driver::control_armRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::driver::control_armRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.base_angle);
      stream.next(m.base_speed);
      stream.next(m.shoulder_angle);
      stream.next(m.shoulder_speed);
      stream.next(m.elbow_angle);
      stream.next(m.elbow_speed);
      stream.next(m.wrist_angle);
      stream.next(m.wrist_speed);
      stream.next(m.gripper_angle);
      stream.next(m.gripper_speed);
      stream.next(m.wrist_rotate_angle);
      stream.next(m.wrist_rotate_speed);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control_armRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::driver::control_armRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::driver::control_armRequest_<ContainerAllocator>& v)
  {
    s << indent << "base_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.base_angle);
    s << indent << "base_speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.base_speed);
    s << indent << "shoulder_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.shoulder_angle);
    s << indent << "shoulder_speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.shoulder_speed);
    s << indent << "elbow_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.elbow_angle);
    s << indent << "elbow_speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.elbow_speed);
    s << indent << "wrist_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.wrist_angle);
    s << indent << "wrist_speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wrist_speed);
    s << indent << "gripper_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gripper_angle);
    s << indent << "gripper_speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gripper_speed);
    s << indent << "wrist_rotate_angle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.wrist_rotate_angle);
    s << indent << "wrist_rotate_speed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wrist_rotate_speed);
    s << indent << "time: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVER_MESSAGE_CONTROL_ARMREQUEST_H
