// Generated by gencpp from file driver/control_armRequest.msg
// DO NOT EDIT!


#ifndef DRIVER_MESSAGE_CONTROL_ARMREQUEST_H
#define DRIVER_MESSAGE_CONTROL_ARMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace driver
{
template <class ContainerAllocator>
struct control_armRequest_
{
  typedef control_armRequest_<ContainerAllocator> Type;

  control_armRequest_()
    : angles()
    , speeds()
    , time(0)  {
    }
  control_armRequest_(const ContainerAllocator& _alloc)
    : angles(_alloc)
    , speeds(_alloc)
    , time(0)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _angles_type;
  _angles_type angles;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _speeds_type;
  _speeds_type speeds;

   typedef uint16_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::driver::control_armRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::driver::control_armRequest_<ContainerAllocator> const> ConstPtr;

}; // struct control_armRequest_

typedef ::driver::control_armRequest_<std::allocator<void> > control_armRequest;

typedef boost::shared_ptr< ::driver::control_armRequest > control_armRequestPtr;
typedef boost::shared_ptr< ::driver::control_armRequest const> control_armRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::driver::control_armRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::driver::control_armRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::driver::control_armRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::driver::control_armRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::driver::control_armRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::driver::control_armRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::driver::control_armRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::driver::control_armRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::driver::control_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2060963bec26b478635ecaf1f13b9fd";
  }

  static const char* value(const ::driver::control_armRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2060963bec26b47ULL;
  static const uint64_t static_value2 = 0x8635ecaf1f13b9fdULL;
};

template<class ContainerAllocator>
struct DataType< ::driver::control_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "driver/control_armRequest";
  }

  static const char* value(const ::driver::control_armRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::driver::control_armRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[] angles\n"
"uint8[] speeds\n"
"uint16 time\n"
;
  }

  static const char* value(const ::driver::control_armRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::driver::control_armRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angles);
      stream.next(m.speeds);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control_armRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::driver::control_armRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::driver::control_armRequest_<ContainerAllocator>& v)
  {
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.angles[i]);
    }
    s << indent << "speeds[]" << std::endl;
    for (size_t i = 0; i < v.speeds.size(); ++i)
    {
      s << indent << "  speeds[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.speeds[i]);
    }
    s << indent << "time: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVER_MESSAGE_CONTROL_ARMREQUEST_H
