(cl:in-package driver-srv)
(cl:export '(BASE_ANGLE-VAL
          BASE_ANGLE
          BASE_SPEED-VAL
          BASE_SPEED
          SHOULDER_ANGLE-VAL
          SHOULDER_ANGLE
          SHOULDER_SPEED-VAL
          SHOULDER_SPEED
          ELBOW_ANGLE-VAL
          ELBOW_ANGLE
          ELBOW_SPEED-VAL
          ELBOW_SPEED
          WRIST_ANGLE-VAL
          WRIST_ANGLE
          WRIST_SPEED-VAL
          WRIST_SPEED
          GRIPPER_ANGLE-VAL
          GRIPPER_ANGLE
          GRIPPER_SPEED-VAL
          GRIPPER_SPEED
          WRIST_ROTATE_ANGLE-VAL
          WRIST_ROTATE_ANGLE
          WRIST_ROTATE_SPEED-VAL
          WRIST_ROTATE_SPEED
          TIME-VAL
          TIME
          SUCCES-VAL
          SUCCES
))